version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MAC_ADDRESS=00:00:00:00:00:00
      - COMPANY_SECRET=abcdefghijklmnop
      - ADMIN_SECRET=1234567890
      - STUDENT_SECRET=0987654321
      - DB_URL=postgres://avnadmin:AVNS_m5c-2q6jI2s31vyGGb8@unbiass-oa-unbiass-oa.c.aivencloud.com:27968/defaultdb?sslmode=require
      - REDIS_HOST=localhost:6379
      - OPENAI_API_KEY=sjssjssjssjssjssjssjssjssjssjssjssjssjss
      - PORT=4000
      - AWS_ACCESS_KEY_ID=AKIAQE5WFURQMF44JDHM
      - AWS_SECRET_ACCESS_KEY=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

